spring.datasource.url=jdbc:mysql://localhost:3306/evaluacion_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=kike123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
server.port=8080

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

app.openapi.title=API de Evaluacion Docente
app.openapi.version=1.0
app.openapi.description=Sistema de evaluacion academica UTVT
app.openapi.contact.name=IDGS-84
app.openapi.contact.email=idgs84@utvt.edu.mx

app.cors.allowed-origins=http://localhost:3000,http://127.0.0.1:3000
